version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq_management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest